// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// 🔑 IMPORTANT: mêmes noms que dans Vite (.env)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug simple (tu peux enlever après)
// console.log("Supabase URL:", SUPABASE_URL);
// console.log("Supabase KEY exists:", !!SUPABASE_ANON_KEY);

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Check VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY"
  );
}

// Client Supabase
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };

  public: {
    Tables: {
      stories: {
        Row: {
          character_name: string;
          character_notes: string | null;
          character_traits: string[] | null;
          content: string;
          cover_url: string | null;
          created_at: string;
          id: string;
          length: string;
          reader_name: string | null;
          reader_notes: string | null;
          reader_traits: string[] | null;
          template: string;
          title: string;
          tones: string[] | null;
          user_id: string;
        };
        Insert: {
          character_name: string;
          character_notes?: string | null;
          character_traits?: string[] | null;
          content: string;
          cover_url?: string | null;
          created_at?: string;
          id?: string;
          length: string;
          reader_name?: string | null;
          reader_notes?: string | null;
          reader_traits?: string[] | null;
          template: string;
          title: string;
          tones?: string[] | null;
          user_id: string;
        };
        Update: {
          character_name?: string;
          character_notes?: string | null;
          character_traits?: string[] | null;
          content?: string;
          cover_url?: string | null;
          created_at?: string;
          id?: string;
          length?: string;
          reader_name?: string | null;
          reader_notes?: string | null;
          reader_traits?: string[] | null;
          template?: string;
          title?: string;
          tones?: string[] | null;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;
type DefaultSchema =
  DatabaseWithoutInternals[Extract<keyof Database, "public">];

// helpers (inchangés)
export type Tables<...> = any;
export type TablesInsert<...> = any;
export type TablesUpdate<...> = any;
export type Enums<...> = any;
export type CompositeTypes<...> = any;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
